### ISSUE TITLE
Rawhide has failing tests

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#1242]
Rawhide seems to be unrelated broken:
```
error: Scrollbar test exception: TypeError: document.body is null
log: PackageKit went away from D-Bus
log: osinfo-detect command failed:  (process:38737): GLib-GIO-WARNING **: 08:20:12.589: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 28, in <module>
gi.repository.GLib.GError: osinfo-tree-error: URL protocol is not supported (1)
log: osinfo-detect command failed:  (process:39253): GLib-GIO-WARNING **: 08:20:28.529: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
error: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    operation failed: Failed to connect to nbdkit for 'https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso': libvirt:  error : cannot execute binary /usr/sbin/nbdkit: Permission denied\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate7\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<stdin>\", line 348, in <module>\n  File \"<stdin>\", line 250, in create_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--memory', '128', '--name', 'subVmTestCreate7', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=::1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"
```

_Originally posted by @jelly in https://github.com/cockpit-project/cockpit-machines/issues/1240#issuecomment-1750199704_

**Comment by martinpitt** [comment]
This got naughtied in https://github.com/cockpit-project/bots/pull/5360
