### ISSUE TITLE
AddDiskModalBody passes invalid size to VolumeCreateBody

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#1273]
This is exposed by [these React errors](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1270-20231027-062752-7b6401ac-fedora-38-devel/log.html) (all four tests fail on the same issue):
```
error: Warning: Failed %s type: %s%s prop Invalid prop `size` of type `string` supplied to `VolumeCreateBody`, expected `number`. 
    at VolumeCreateBody (http://127.0.0.2:9091/cockpit/@localhost/machines/index.js:130756:5)
    at CreateNewDisk (http://127.0.0.2:9091/cockpit/@localhost/machines/index.js:133599:5)
   [...]
    at AddDiskModalBody (http://127.0.0.2:9091/cockpit/@localhost/machines/index.js:133718:7)
```

This is a real bug. In most cases, the passed property is the default from `initState`:
```
> log: XXX AddDiskModalBody.render size {"type":"number","value":1,"description":"1"}
```
but during testAddDiskDirPool() it becomes:
```
> log: XXX AddDiskModalBody.render size 2
```
i.e. a string. It's not really clear to me where this gets set, there is no direct setState() call.

I'll keep ignoring this specific log message for now, but this should be fixed. In particular, `AddDiskModalBody` also has a state `unit`, which is entirely ignored when passing the size to VolumeCreateBody.

**Comment by martinpitt** [comment]
Fixing this should become much easier after PR #1303, as the state is less entangled.

**Comment by martinpitt** [comment]
This happens when deleting the "Size" field, or selecting all and replacing it with e.g. "2".
