### ISSUE TITLE
Rawhide test failures

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#1294]
### Snapshots revert

```
Traceback (most recent call last):
  File "/home/jelle/projects/cockpit-machines/./test/check-machines-snapshots", line 285, in testSnapshotRevert
    b.wait_visible("#vm-subVmTest1-snapshot-0-current")
  File "/home/jelle/projects/cockpit-machines/test/common/testlib.py", line 618, in wait_visible
    self._wait_present(selector)
  File "/home/jelle/projects/cockpit-machines/test/common/testlib.py", line 609, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/jelle/projects/cockpit-machines/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/jelle/projects/cockpit-machines/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/jelle/projects/cockpit-machines/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-snapshot-0-current")): Uncaught (in promise) Error: condition did not become true
```

```
> warning: GET_VM failed for /org/libvirt/QEMU/domain/_88a43112_22c0_43d9_9848_5ff0828b85e2, undefining: Cannot recv data: Connection reset by peer
```

### testHostDevAddSingleDevice

Locally
```
audit: type=1400 audit(1699378740.302:509): avc:  denied  { create } for  pid=2599 comm="qemu-system-i38" anonclass=[io_uring] scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:io_uring_t:s0 tclass=anon_inode permissive=1
````

**Comment by martinpitt** [comment]
Two recent example logs:
 - https://artifacts.dev.testing-farm.io/0aa53011-f549-412e-bb65-792d6ca6a3b7/
 - https://artifacts.dev.testing-farm.io/0a63986c-a4fa-4872-9e67-d1f8abdd496d/

**Comment by martinpitt** [comment]
snapshotRevert failure sounds similar to https://github.com/cockpit-project/bots/issues/5494 , but that naughty already exists for rawhide: https://github.com/cockpit-project/bots/blob/main/naughty/fedora-40/5494-libvirt-snapshot-revert-crash

However, for some reason you copied the wrong output: The pattern is for "snapshot-0-current", but in the above logs it fails on "snapshot-1-current". The [journal](https://artifacts.dev.testing-farm.io/0aa53011-f549-412e-bb65-792d6ca6a3b7/work-storage2nca4ncp/plans/all/storage/execute/data/guest/default-0/test/browser/storage-1/data/TestMachinesSnapshots-testSnapshotRevert-fedora-40-localhost-22-FAIL.log.gz) doesn't have systemd-coredump, but it does have similar error messages:
```
Nov 06 21:51:09 ip-172-31-21-107.us-east-2.compute.internal virtqemud[32491]: Unable to read from monitor: Connection reset by peer
Nov 06 21:51:09 ip-172-31-21-107.us-east-2.compute.internal virtqemud[32491]: internal error: QEMU unexpectedly closed the monitor (vm='subVmTest1'): qemu-system-x86_64: ../block/io.c:1957: bdrv_co_write_req_prepare: Assertion `!(bs->open_flags & BDRV_O_INACTIVE)' failed.
Nov 06 21:51:09 ip-172-31-21-107.us-east-2.compute.internal systemd-machined[5235]: Machine qemu-2-subVmTest1 terminated.
[...]
virtqemud[32491]: End of file while reading data: Input/output error
```
So in the best case this just needs a little pattern adjustment?

**Comment by jelly** [comment]
testHostDevAddSingleDevice and the other related one is basically https://github.com/cockpit-project/cockpit-machines/issues/1292

**Comment by martinpitt** [comment]
The snapshot test was fixed via a naughty, let's handle the host-dev failures in #1292
