### ISSUE TITLE
wait_in_text("body", "Virtual machines") failed in aarch64

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#1523]
When running automation with aarch64, there will be a "raise T" in waitPageInit -> self.browser.wait_in_text("body", "Virtual machines"). Also, add some details from the automation log
{"exceptionId":1,"text":"Uncaught (in promise)","lineNumber":696,"columnNumber":9103,"scriptId":"36","url":"http://10.6.6.171:9090/cockpit/@localhost/machines/index.js","stackTrace":{"callFrames":[{"functionName":"","scriptId":"36","url":"http://10.6.6.171:9090/cockpit/@localhost/machines/index.js","lineNumber":696,"columnNumber":9103}]},"exception":{"type":"object","className":"T","description":"T","objectId":"3545638390102327573.8.1","preview":{"type":"object","description":"T","overflow":false,"properties":[{"name":"problem","type":"object","value":"null","subtype":"null"},{"name":"exit_status","type":"number","value":"1"},{"name":"exit_signal","type":"object","value":"null","subtype":"null"},{"name":"message","type":"string","value":""},{"name":"toString","type":"function","value":""}]}},"executionContextId":8}

**Comment by martinpitt** [comment]
Which test was that? Note that the current tests don't really work on non-x86, as we only have an x86 cirros image. See the corresponding [jira issue](https://issues.redhat.com/browse/COCKPIT-970?focusedId=24404027&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24404027) this is unfortunately hard to fix, and we don't currently have anyone who could look into it.

**Comment by yunmingyang** [comment]
Sorry the machine is returned. If my memory is correct, it seems that all cases with self.waitPageInit() will raise this error, even though I annotated self.waitPageInit(), the error will also be raised in next wait_xxx. I will re-provision a machine and try it again, then leave a new comment. And for the image, I use this(http://download.cirros-cloud.net/0.6.2/) directly. Also, according to https://github.com/cockpit-project/cockpit/issues/9935, modify the /etc/cirros-init/config. I try this image manually. It could be run correctly. And one difference is, the minimal memory could not be 128 as OOM, I set it to 256, the VM could be booted successfully. Also, it seems that the VNC console could not be input in aarch64, I will also try it in the new provision machine.

**Comment by yunmingyang** [comment]
So I try with testSerialConsole, and the case will fail in self.waitPageInit(), here is the Traceback
```
Traceback (most recent call last):
  File "/home/yunyang/github/cockpit-machines/test/check-machines-consoles", line 105, in testSerialConsole
    self.waitVmRow(name)
  File "/home/yunyang/github/cockpit-machines/test/machineslib.py", line 95, in waitVmRow
    b.wait_visible(vm_row)
  File "/home/yunyang/github/cockpit-machines/test/common/testlib.py", line 648, in wait_visible
    self._wait_present(selector)
  File "/home/yunyang/github/cockpit-machines/test/common/testlib.py", line 639, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/yunyang/github/cockpit-machines/test/common/testlib.py", line 633, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/yunyang/github/cockpit-machines/test/common/testlib.py", line 630, in wait_js_cond
    raise e
  File "/home/yunyang/github/cockpit-machines/test/common/testlib.py", line 610, in wait_js_cond
    result = self.cdp.invoke("Runtime.evaluate",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yunyang/github/cockpit-machines/test/common/cdp.py", line 204, in invoke
    res = self.command(cmd)
          ^^^^^^^^^^^^^^^^^
  File "/home/yunyang/github/cockpit-machines/test/common/cdp.py", line 231, in command
    raise RuntimeError(res["error"])
RuntimeError: T
Wrote vmWithSerialConsole log to TestMachinesConsoles-testSerialConsole-rhel-9-5-10.26.2.97-22-vmWithSerialConsole.log
```

**Comment by yunmingyang** [comment]
Also try with VNC console, I could input anything with it, but the input is OK with Serial console. And according to https://bugzilla.redhat.com/show_bug.cgi?id=1673330, I check the VM XML, 
```
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='keyboard' bus='usb'>
      <alias name='input1'/>
      <address type='usb' bus='0' port='2'/>
    </input>
```
It seems that the related XML is also there. So maybe we need some more investigation when we have time.

**Comment by martinpitt** [comment]
@yunmingyang that smells like the page wouldn't load at all. I bet if you check the screenshot you either see a white page or the "loading" spinner.

**Comment by yunmingyang** [comment]
@martinpitt  Emmm...Yeah it will be the white page for a while(maybe thirty seconds), then the page is loaded, then the VM list page will be shown after some seconds. And actually, I didn't see this issue by manual. Only meet it when running the automation

**Comment by yunmingyang** [comment]
I think I found the root cause of this error. I built a package with enabling sourceMap, then re-run the case with chrome, some changes for the error, which is T -> ProcessError. Then I try with firefox, there are some more details for the error
```
RuntimeError: {"exceptionId":0,"text":"uncaught exception: Object","lineNumber":148170,"columnNumber":56,"url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","stackTrace":{"callFrames":[{"functionName":"App/</<","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":148170,"columnNumber":56},{"functionName":"AsyncFunctionThrow","scriptId":"0","url":"self-hosted","lineNumber":856,"columnNumber":27},{"functionName":"App/<","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":148172,"columnNumber":8},{"functionName":"commitHookEffectListMount","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":18817,"columnNumber":36},{"functionName":"commitPassiveMountOnFiber","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":20070,"columnNumber":43},{"functionName":"commitPassiveMountEffects_complete","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":20038,"columnNumber":43},{"functionName":"commitPassiveMountEffects_begin","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":20028,"columnNumber":50},{"functionName":"commitPassiveMountEffects","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":20018,"columnNumber":43},{"functionName":"flushPassiveEffectsImpl","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":21399,"columnNumber":37},{"functionName":"flushPassiveEffects","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":21356,"columnNumber":23},{"functionName":"node_modules/react-dom/cjs/react-dom.development.js/commitRootImpl/<","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":21237,"columnNumber":18},{"functionName":"workLoop","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2110,"columnNumber":51},{"functionName":"flushWork","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2089,"columnNumber":23},{"functionName":"performWorkUntilDeadline","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2297,"columnNumber":30},{"functionName":"node_modules/scheduler/cjs/scheduler.development.js/<","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2318,"columnNumber":12},{"functionName":"node_modules/scheduler/cjs/scheduler.development.js","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2366,"columnNumber":10},{"functionName":"__require","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":9,"columnNumber":51},{"functionName":"node_modules/scheduler/index.js","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2378,"columnNumber":25},{"functionName":"__require","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":9,"columnNumber":51},{"functionName":"node_modules/react-dom/cjs/react-dom.development.js/<","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":2394,"columnNumber":26},{"functionName":"node_modules/react-dom/cjs/react-dom.development.js","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":23469,"columnNumber":10},{"functionName":"__require","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":9,"columnNumber":51},{"functionName":"node_modules/react-dom/index.js","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":23482,"columnNumber":25},{"functionName":"__require","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":9,"columnNumber":51},{"functionName":"node_modules/react-dom/client.js","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":23491,"columnNumber":14},{"functionName":"__require","scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":9,"columnNumber":51},{"functionName":null,"scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":47262,"columnNumber":30},{"functionName":null,"scriptId":"0","url":"http://10.6.6.30:9090/cockpit/@localhost/machines/index.js","lineNumber":148401,"columnNumber":2}]},"executionContextId":3}
```
Then I found that there is a line number of index.js. Then I check the line, it is
```
(0, import_react102.useEffect)(() => {
      (async () => {
        const hardwareVirtCheck = await cockpit_default.script("virt-host-validate | grep 'Checking for hardware virtualization'");
        setVirtualizationEnabled(hardwareVirtCheck.includes("PASS"));
      })();
}, []);
```
According that, I think the root cause is the difference about the output of virt-host-validate between aarch64 and x86_64. In aarch64, the output of virt-host-validate should be like
```
# virt-host-validate 
  QEMU: Checking if device /dev/kvm exists                                   : FAIL (Check that CPU and firmware supports virtualization and kvm module is loaded)
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : PASS
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)
```
The VM could be run successfully though it seems that there is some trouble for virtualization support according to the output. Thus, I built a rpm without verification about virt-host-validate, the automation case could pass.

**Comment by martinpitt** [comment]
Thanks @yunmingyang ! I sent PR #1543 to fix this.
