### ISSUE TITLE
Building from Source Error

### ISSUE THREAD

**Issue by jradxl** [cockpit-project/cockpit-machines#1527]
I'm using Ubuntu Jammy 22.04 and have installed Cockpit-Machine via backports which is v307
I have tried to build from your source to get at least 310 which has the Tap network feature I believe.
However I get a build error
```
$ make
remote: Enumerating objects: 1529, done.
remote: Counting objects: 100% (1529/1529), done.
remote: Compressing objects: 100% (1351/1351), done.
remote: Total 1529 (delta 260), reused 614 (delta 90), pack-reused 0
Receiving objects: 100% (1529/1529), 7.46 MiB | 10.25 MiB/s, done.
Resolving deltas: 100% (260/260), done.
git archive 'f2cc9e1a360e69dc55b8f9f26f367eb4c17ecb5b^{tree}' -- pkg/lib test/common test/static-code tools/node-modules  | tar x
make package-lock.json && NODE_ENV= ./build.js
make[1]: Entering directory '/home/jradley/Devel/cockpit-machines'
tools/node-modules make_package_lock_json
  FETCH    node_modules  [ref: 31b5a4b1d5753e15cfd145cabd8c9716d9f5b5c0]
  REMOVE   node_modules
  CLONE    node_modules  [ref: 31b5a4b1d5753e15cfd145cabd8c9716d9f5b5c0]
  COPY     package-lock.json
make[1]: Leaving directory '/home/jradley/Devel/cockpit-machines'
file:///home/jradley/Devel/cockpit-machines/build.js:17
const esbuild = (await import(useWasm ? 'esbuild-wasm' : 'esbuild'));
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make: *** [Makefile:98: dist/manifest.json] Error 1

```
Are your build instructions correct?
Am I missing a dependency?

Thanks
John

**Comment by jradxl** [comment]
Ah, Node in Jammy is v12 !!
I installed Node v21 with NVM and have a build.
I've added the new Cockpit Machine to my Cockpit Web installation, but it doesnt have the Tap features I was hoping for,

**Comment by martinpitt** [comment]
Right, you need at least nodejs 16, unfortunately Ubuntu 22.04 has an ancient one. You can use [n](https://www.npmjs.com/package/n) or [our official dev container](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container)
