### ISSUE TITLE
Virtual Machine stuck "Loading resources"

### ISSUE THREAD

**Issue by adds68** [cockpit-project/cockpit-machines#368]
Hi there,

I am having issues getting the virtual machines plugin to work, as it stays on the "Loading resources" screen.

Some background of my setup:

Fedora 33

Cockpit:
Version: 251
Protocol: 1
Payloads: dbus-json3 http-stream1 http-stream2 stream packet fsread1 
    fsreplace1 fswatch1 fslist1 null echo websocket-stream1 
Authorization: crypt1

I am using virsh to manage the VMs, I am not entirely sure if that is correct.

The VMs are running but i have to manually start them using virsh via the cockpit terminal.

Is there anything obvious i may have miss-configured or am missing?

**Comment by KKoukiou** [comment]
Do you see any errors in your browser console? (Right click -> Inspect -> Console tab)

**Comment by KKoukiou** [comment]
Also useful would be to check the output `$ systemctl status libvirtd` in your terminal (or check libvirtd service in cockpit's services page)

**Comment by adds68** [comment]
> Do you see any errors in your browser console? (Right click -> Inspect -> Console tab)
> 
> ( I am sure the issue is on our side - there is nothing your can misconfigure - let's find it out :))

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.1.244:9090
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 index.js:2:120323
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). index.js:2:120555
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). index.js:2:131133
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”). 3 blob:27:22
Modal: Specify at least one of: title, aria-label, aria-labelledby. 2 index.js:2:475513
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. index.html
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. index.html
grep: /sys/class/dmi/id/board_serial: Permission denied
grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied
cockpit.js:1:8085
Modal: Specify at least one of: title, aria-label, aria-labelledby. overview.js:2:921907
Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined" updates.js:2:1155400
Could not determine kpatch availability: {"detail":"Failed to obtain authentication.","code":48} updates.js:2:505259
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. services.html
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”). blob:27:22
metrics closed: 
Object { command: "close", channel: "1:5!5" }
index.js:2:463949
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”). blob:27:22
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. index.html
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build. index.js:2:321291
Scrollbar test exception: TypeError: document.body is null index.js:2:1615049
XML Parsing Error: syntax error
Location: https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.html#/
Line Number 1, Column 1: index.html:1:1
Uncaught TypeError: t.getElementsByTagName(...)[0] is undefined
    t https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.js:2
    Cg https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.js:2
    N https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
    N https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
    A https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
index.js:2:1349545
XML Parsing Error: syntax error
Location: https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.html#/
Line Number 1, Column 1: index.html:1:1
Uncaught TypeError: t.getElementsByTagName(...)[0] is undefined
    t https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.js:2
    Cg https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.js:2
    N https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
    N https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
    A https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/base1/cockpit.js:1
index.js:2:1349545
<stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.
cockpit.js:1:8085
Source map error: Error: request failed with status 404
Resource URL: https://192.168.1.244:9090/cockpit/$21d6a9fd1ed8f0af405b898abbf0292c89fa4d97b20b4b39754c0a25268d49f2/machines/index.js
Source Map URL: index.js.map

```

**Comment by adds68** [comment]
> Also useful would be to check the output `$ systemctl status libvirtd` in your terminal (or check libvirtd service in cockpit's services page)

```
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-10 08:12:07 BST; 1 day 8h ago
TriggeredBy: ● libvirtd.socket
             ● libvirtd-ro.socket
             ● libvirtd-admin.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
   Main PID: 9341 (libvirtd)
      Tasks: 21 (limit: 32768)
     Memory: 62.1M
        CPU: 10.335s
     CGroup: /system.slice/libvirtd.service
             ├─1518 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
             ├─1523 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
             └─9341 /usr/sbin/libvirtd --timeout 120

Sep 10 08:12:07 localhost.localdomain systemd[1]: Started Virtualization daemon.
Sep 10 08:12:07 localhost.localdomain dnsmasq[1518]: read /etc/hosts - 2 addresses
Sep 10 08:12:07 localhost.localdomain dnsmasq[1518]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Sep 10 08:12:07 localhost.localdomain dnsmasq-dhcp[1518]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Sep 10 08:12:24 localhost.localdomain libvirtd[9538]: 2021-09-10 07:12:24.993+0000: 9538: info : libvirt version: 6.6.0, package: 5.fc33 (Fedora Project, 2020-12-07-17:58:21, )
Sep 10 08:12:24 localhost.localdomain libvirtd[9538]: 2021-09-10 07:12:24.993+0000: 9538: info : hostname: localhost.localdomain
Sep 10 08:12:24 localhost.localdomain libvirtd[9538]: 2021-09-10 07:12:24.993+0000: 9538: warning : virSecurityValidateTimestamp:195 : Invalid XATTR timestamp detected on /var/lib/libvirt/images/pihole.qcow2 secdriver=selinux
Sep 10 08:12:24 localhost.localdomain libvirtd[9539]: 2021-09-10 07:12:24.996+0000: 9539: info : libvirt version: 6.6.0, package: 5.fc33 (Fedora Project, 2020-12-07-17:58:21, )
Sep 10 08:12:24 localhost.localdomain libvirtd[9539]: 2021-09-10 07:12:24.996+0000: 9539: info : hostname: localhost.localdomain
Sep 10 08:12:24 localhost.localdomain libvirtd[9539]: 2021-09-10 07:12:24.996+0000: 9539: warning : virSecurityValidateTimestamp:195 : Invalid XATTR timestamp detected on /var/lib/libvirt/images/pihole.qcow2 secdriver=dac
```

**Comment by adds68** [comment]
Thanks for the quick response! Libvirtd seems fine, however as you can see there is a lot of error/warnings in my developer console!

**Comment by KKoukiou** [comment]
@adds68 the issue is that it crashes when trying to parse the XML from one of your resources. 

In order to fix this I need to see a proper traceback, which I can get if you do one of the three options:

* Give me all your VMs, Networks, Pools and other libvirt resources XMLs files you have, so I can reproduce it in my env
* Or build cockpit from sources, so that we get a developement mode traceback
* Or I can build the RPM for you with a developement build and you can  install the latter

Let me know what you prefer. (and thanks for reporting)

**Comment by adds68** [comment]
Thank you, I did not spot that XML error.

I can provide you with the XML files, i don't mind building from source but would need some more time, so i guess providing the xml files would be easier.

What files/where are they located?

**Comment by KKoukiou** [comment]
@adds68 basically all VMs, Networks, Pools etc, your libvirt resources. You can share a tarball of /etc/libvirt/qemu for start. Thanks :)

**Comment by KKoukiou** [comment]
@adds68 any update on this :)?

**Comment by adds68** [comment]
Hi @KKoukiou! Sorry for the delay, i had a busy week and also had to learn how SCP works xD


I've attached a zip of my Qemu directory, please let me know if there is anything else needed.

[etc.zip](https://github.com/cockpit-project/cockpit-machines/files/7198379/etc.zip)

**Comment by KKoukiou** [comment]
Hey @adds68 I just created a VM based on your pihole VM that you posted above and I did not get the crash. So it's maybe related to your host devices that I can't see on my machine. 

So since this is the case - and I can't reproduce the only way to know more details about the crash are the two other ways I propose above :/ Are you willing to try out building cockpit-machines from source? If you need help on that you can step on our IRC channel on #cockpit at libera and  I can guide you into this. https://www.irccloud.com/irc/libera.chat/channel/cockpit

**Comment by adds68** [comment]
Hey @KKoukiou , interesting, i wonder why that is.

Sure i don't mind building that from source, i'd probably need help then ensuring i am using the version i built etc within cockpit.

But i will join the IRC channel :)

**Comment by KKoukiou** [comment]
This is a pretty old issue, and we have refactored this part of the code, that handles the loading page massively. Closing this, but if you encounter it still please reopen and comment on the used cockpit version.

thanks :)

**Comment by carrowood** [comment]
Hmmm.  I seem to be having this same issue, I think.  When I select "Virtual Machines" from the menu it just spins with "Loading Resources". I am probably doing something dumb, lol.  Some details:
cockpit-304-1.fc39
cockpit-machines-301.1-1.fc39

Console Log:
[Chrome-Console-192.168.1.50-1699847807553.log](https://github.com/cockpit-project/cockpit-machines/files/13330606/Chrome-Console-192.xxxx-1699847807553.log)

Qemu XML's:
[qemu.tar.gz](https://github.com/cockpit-project/cockpit-machines/files/13330698/qemu.tar.gz)

**Comment by martinpitt** [comment]
@carrowood Your linked console log does not exist. Can you please create a new issue and attach or just paste in the console log? Thanks!
