### ISSUE TITLE
TestMachinesCreate.testCreateThenInstall often fails on Testing Farm

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#526]
On CentOS-9-Stream, we are getting an awful lot of failures:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/var/ARTIFACTS/work-allfLW1WD/plans/all/discover/default/tests/test/check-machines-create", line 416, in testCreateThenInstall
    runner.createThenInstallTest(TestMachinesCreate.VmDialog(self, sourceType='file',
  File "/var/ARTIFACTS/work-allfLW1WD/plans/all/discover/default/tests/test/check-machines-create", line 1453, in createThenInstallTest
    self._tryCreateThenInstall(dialog, installFromVmDetails, tryWithFailInstall) \
  File "/var/ARTIFACTS/work-allfLW1WD/plans/all/discover/default/tests/test/check-machines-create", line 1347, in _assertDomainDefined
    wait(lambda: "7" in self.run_admin(dumpxmlCmd + " | grep cockpit_machines | wc -l", connection))
  File "/var/ARTIFACTS/work-allfLW1WD/plans/all/discover/default/tests/test/common/testlib.py", line 1993, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
```

[example 1](http://artifacts.dev.testing-farm.io/540595d1-8378-486d-a0da-cd64570db6ba/), [example 2](http://artifacts.dev.testing-farm.io/26e777f2-ea3c-472a-b839-8c0f362be187/), [example 3](http://artifacts.dev.testing-farm.io/a7618146-1917-492b-99af-024e7db4297c/). There are still no artifacts, so hard to tell what's wrong -- but this needs debugging. Most likely we'll need to disable that test from fmf for the time being.

**Comment by martinpitt** [comment]
Let's discuss in #581, this has more information.
